### ISSUE TITLE
CaliStar.target_star broken

### ISSUE THREAD

**Issue by mileslucas** [tomasstolker/calistar#2]
Type checking error for `Calistar.target_star` I discovered following the tutorial
```python
>>> cal_star = CaliStar(gaia_source=156917493449670656, gaia_release="DR3")
>>> target_prop = cal_star.target_star(write_json=True, get_gaiaxp=False)
[...]
TypeError                                 Traceback (most recent call last)
----> 1 target_prop = cal_star.target_star(write_json=True, get_gaiaxp=False)

File ~/mambaforge/lib/python3.10/site-packages/typeguard/__init__.py:1037, in typechecked.<locals>.wrapper(*args, **kwargs)
   1035     check_return_type(retval, memo)
   1036 except TypeError as exc:
-> 1037     raise TypeError(*exc.args) from None
   1039 # If a generator is returned, wrap it if its yield/send/return types can be checked
   1040 if inspect.isgenerator(retval) or isasyncgen(retval):

TypeError: type of the return value['Gaia RA'] must be one of (str, float); got tuple instead
```

**Comment by tomasstolker** [comment]
Thanks for opening the issue! I can't reproduce it... Could you please share the full traceback of the error message?

**Comment by tomasstolker** [comment]
Could you try once more with the latest version from Github? That should hopefully fix it! Not sure why the error did not happen on my end, perhaps I a using an older version of `typeguard`.

**Comment by mileslucas** [comment]
Thanks for the quick look and fix-
> Could you try once more with the latest version from GitHub

This version appears to be working fine; I can call `.target_star,` `.find_calib`, and `.select_calib` without any issues on my target now.
